name: Varredura de segredos GitGuardian

on: [pull_request]

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - name: Checando  codigo
        uses: actions/checkout@v3

      - name: Instalando ggshield
        run: pip install ggshield

      - name: Scaneando os segredos do PR
        run: ggshield scan pr
